# Generated by Django 4.1.7 on 2023-04-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('review', models.TextField(max_length=500)),
            ],
        ),
    ]
