# Generated by Django 4.1.7 on 2023-04-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Management', '0002_books_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='link',
        ),
    ]
