# Generated by Django 4.1.7 on 2023-04-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Management', '0003_remove_books_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('review', models.TextField(max_length=500)),
            ],
        ),
    ]
