# Generated by Django 4.1.7 on 2023-04-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.TextField(default='', max_length=500),
        ),
    ]
